version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'true'
      PRODUCTION: 'true'
      ROOT_URL: 'http://localhost'
      ROOT_HOST: 't1m.me'
      EXTRA_TRUSTED_ORIGINS: ''
      DJANGO_SECRET_KEY: 'SomeSecret'
      DJANGO_ALLOWED_HOSTS: '*'
      REDIS_URL: 'redis://host.docker.internal:6379'
      USE_NEXTJS_PROXY_ROUTES: 'true'
      NEXTJS_HOST_URL: 'http://frontend:3000'
      BASE_ADMIN_USERNAME: 'admin'
      BASE_ADMIN_USER_PASSWORD: 'password'
    volumes:
      - ./backend:/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      ROOT_URL: 'http://localhost'
      WEBSOCKET_PROTOCOL: 'ws://'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mariadb:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'timeme'
      MYSQL_USER: 'timeme'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./matomo/mariadb:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  matomo:
    image: matomo
    ports:
      - "8080:80"
    environment:
      MATOMO_DATABASE_HOST: 'host.docker.internal:3306'
      MATOMO_DATABASE_USERNAME: 'timeme'
      MATOMO_DATABASE_PASSWORD: 'password'
      MATOMO_DATABASE_DBNAME: 'timeme'
      MATOMO_DATABASE_TABLES_PREFIX: 'matomo_'
    volumes:
      - ./matomo/html/config:/var/www/html/config/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    